# Hexo Configuration
## Docs: https://hexo.io/zh-cn/docs/configuration.html
## Source: https://github.com/hexojs/hexo/
title: 过客
author: passwhl
language: zh-CN
url: https://b.wguan.top
root: /
permalink: :year/:month/:day/:title/
skip_render: [README.md,CNAME]
per_page: 10
theme: next
deploy:
  type: git
  repo: git@github.com:passwhl/passwhl.github.io.git
  branch: master
